/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Cadastro_GUI extends javax.swing.JFrame {

    //------------
    static int cpf;
    static String nom;
    static String email;
    String url = "jdbc:mysql://localhost/XEPA"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "";  // senha do BD
    //-------------
    
    
    //código---
    
    public static DefaultTableModel  clientes(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("Código");
            columnNames.addElement("Nome");
            columnNames.addElement("CPF");
            columnNames.addElement("Email");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
        }
        }

    
    //código---
    
    
    //codigo2---
    
    public void refresh(){
    
try{
   Connection conn;
          conn = (Connection) DriverManager.getConnection(url, username, password);
    //Controller.Conecta_BD.carregaDriver();
     
    
    System.out.println("realizado");
            String sql = "SELECT * FROM clientes;";
PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
ResultSet rs = pst.executeQuery();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}    
    } 

    
    //codigo2---
    
    
    
    public Cadastro_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cpf_cad = new org.edisoncor.gui.textField.TextField();
        email_cad = new org.edisoncor.gui.textField.TextField();
        nome_cad = new org.edisoncor.gui.textField.TextField();
        cadastrar_BTN = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven1 = new org.edisoncor.gui.button.ButtonSeven();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cadastromenu.png"))); // NOI18N
        panelImage1.setLayout(null);

        labelMetric1.setBackground(new java.awt.Color(204, 0, 0));
        labelMetric1.setForeground(new java.awt.Color(0, 102, 204));
        labelMetric1.setText("Cadastrar Cliente");
        labelMetric1.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric1.setFont(new java.awt.Font("Comic Sans MS", 1, 31)); // NOI18N
        panelImage1.add(labelMetric1);
        labelMetric1.setBounds(160, 20, 270, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("CPF:");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(120, 150, 80, 20);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Email:");
        panelImage1.add(jLabel2);
        jLabel2.setBounds(120, 230, 80, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(120, 70, 80, 20);

        cpf_cad.setForeground(new java.awt.Color(51, 51, 51));
        cpf_cad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelImage1.add(cpf_cad);
        cpf_cad.setBounds(120, 170, 250, 30);

        email_cad.setForeground(new java.awt.Color(51, 51, 51));
        email_cad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelImage1.add(email_cad);
        email_cad.setBounds(120, 250, 250, 30);

        nome_cad.setForeground(new java.awt.Color(51, 51, 51));
        nome_cad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelImage1.add(nome_cad);
        nome_cad.setBounds(120, 90, 250, 30);

        cadastrar_BTN.setBackground(new java.awt.Color(0, 102, 204));
        cadastrar_BTN.setText("Cadastrar");
        cadastrar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(cadastrar_BTN);
        cadastrar_BTN.setBounds(290, 300, 190, 30);

        buttonSeven1.setBackground(new java.awt.Color(0, 102, 204));
        buttonSeven1.setText("Voltar");
        buttonSeven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven1ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonSeven1);
        buttonSeven1.setBounds(110, 300, 170, 30);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 590, 340);

        setSize(new java.awt.Dimension(590, 343));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_BTNActionPerformed
        nom = nome_cad.getText();
        email = email_cad.getText();
        cpf = Integer.parseInt(cpf_cad.getText());// recebendo o telefone
       Controller.Conecta_BD.carregaDriver();
        try { 
               
        Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(Cadastro_GUI.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

            // Recebendo os dados a serem inseridos na tabela
            String sql = "INSERT INTO clientes(nome_cli, email_cli, cpf_cli) VALUES ('"+nom+"','"+email+"','"+cpf+"')";
     
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção

  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                nome_cad.setText("");
                email_cad.setText("");
                cpf_cad.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!","ERRO!",0);
            }

        }catch(NumberFormatException erro){
        // Tratamento de erro caso o usuario não digite o telefone corretamente
        JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
        nome_cad.setText("");
        email_cad.setText("");
        cpf_cad.setText("");
}refresh();
    }//GEN-LAST:event_cadastrar_BTNActionPerformed

    private void buttonSeven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven1ActionPerformed
        dispose();
        new Menu_GUI().setVisible(true);
    }//GEN-LAST:event_buttonSeven1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven buttonSeven1;
    private org.edisoncor.gui.button.ButtonSeven cadastrar_BTN;
    public static org.edisoncor.gui.textField.TextField cpf_cad;
    public static org.edisoncor.gui.textField.TextField email_cad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    public static org.edisoncor.gui.textField.TextField nome_cad;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
