/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author user
 */
public class Login_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Splash_GUI
     */
    public Login_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        entrar_BTN = new org.edisoncor.gui.button.ButtonRound();
        fechar_BTN = new org.edisoncor.gui.button.ButtonSeven();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        panelImage2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("XEPA");
        panelImage2.add(jLabel1);
        jLabel1.setBounds(230, 60, 150, 40);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");
        panelImage2.add(jLabel2);
        jLabel2.setBounds(160, 190, 60, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Usuário:");
        panelImage2.add(jLabel3);
        jLabel3.setBounds(160, 140, 80, 20);

        usuario.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        panelImage2.add(usuario);
        usuario.setBounds(160, 160, 270, 20);

        senha.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        panelImage2.add(senha);
        senha.setBounds(160, 210, 270, 19);

        entrar_BTN.setBackground(new java.awt.Color(0, 153, 204));
        entrar_BTN.setText("Entrar");
        entrar_BTN.setColorDeSombra(new java.awt.Color(0, 102, 204));
        entrar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_BTNActionPerformed(evt);
            }
        });
        panelImage2.add(entrar_BTN);
        entrar_BTN.setBounds(230, 270, 132, 25);

        fechar_BTN.setBackground(new java.awt.Color(204, 0, 0));
        fechar_BTN.setForeground(new java.awt.Color(0, 0, 0));
        fechar_BTN.setText("X");
        fechar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechar_BTNActionPerformed(evt);
            }
        });
        panelImage2.add(fechar_BTN);
        fechar_BTN.setBounds(550, 10, 30, 30);

        getContentPane().add(panelImage2);
        panelImage2.setBounds(0, 0, 590, 340);

        setSize(new java.awt.Dimension(590, 343));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_BTNActionPerformed
        this.dispose();
        Model.Login_DAO.entrar_funcao();
        
    }//GEN-LAST:event_entrar_BTNActionPerformed

    private void fechar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechar_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fechar_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound entrar_BTN;
    private org.edisoncor.gui.button.ButtonSeven fechar_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    public static javax.swing.JPasswordField senha;
    public static javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
