/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author user
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastrar_menu = new javax.swing.JMenuItem();
        caixa_menu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        voltar_menu = new javax.swing.JMenuItem();
        sair_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        panelImage1.setLayout(null);
        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 590, 320);

        jMenu1.setText("Mercado");

        cadastrar_menu.setText("Cadastrar Cliente");
        cadastrar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_menuActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrar_menu);

        caixa_menu.setText("Ir para o caixa");
        caixa_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_menuActionPerformed(evt);
            }
        });
        jMenu1.add(caixa_menu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tela");

        voltar_menu.setText("Voltar");
        voltar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_menuActionPerformed(evt);
            }
        });
        jMenu2.add(voltar_menu);

        sair_menu.setText("Sair");
        sair_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_menuActionPerformed(evt);
            }
        });
        jMenu2.add(sair_menu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(590, 343));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_menuActionPerformed
        dispose();
        new Login_GUI().setVisible(true);
        
    }//GEN-LAST:event_voltar_menuActionPerformed

    private void sair_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_menuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_menuActionPerformed

    private void cadastrar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_menuActionPerformed
        dispose();
        new Cadastro_GUI().setVisible(true);
        
    }//GEN-LAST:event_cadastrar_menuActionPerformed

    private void caixa_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_menuActionPerformed
        dispose();
        new Caixa_GUI().setVisible(true);
        
    }//GEN-LAST:event_caixa_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrar_menu;
    private javax.swing.JMenuItem caixa_menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JMenuItem sair_menu;
    private javax.swing.JMenuItem voltar_menu;
    // End of variables declaration//GEN-END:variables
}
