/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class Splash_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public Splash_GUI() {
        initComponents();
        
        //-----> inicio código splash
        
        new Thread(){
       
           public void run() {
       
       
       for (int i=0; i<101; i++){
                   try {
                       sleep(60);
                       
                       progress.setValue(i);
                       
                       if(progress.getValue() == 10){
                           porcentagem.setText(i +" %");
                           
                           
                           sleep(2000);
                                                       
                       
                       }else if (progress.getValue() <=30){
                           porcentagem.setText(i +" %");
                           
                         sleep(100);  
                       } else if (progress.getValue() <=99){
                           
                           porcentagem.setText(i +" %");
                       }else{
                           
                           porcentagem.setText(i +" %");
                       sleep(3000);
                       dispose();
                       new Login_GUI().setVisible(true);
                       }
                       
                       
                   } catch (InterruptedException ex) {
                       Logger.getLogger(Splash_GUI.class.getName()).log(Level.SEVERE, null, ex);
                   }
       }        
       }
       
       }.start();
        
   

        //-----> fim código splash
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        porcentagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setBackground(new java.awt.Color(64, 140, 244));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/splash2.png"))); // NOI18N
        panelImage1.setLayout(null);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/splash.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage2);
        panelImage2.setBounds(70, 50, 350, 140);

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/splash3.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage3);
        panelImage3.setBounds(180, 290, 150, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        jLabel1.setText("FROM");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(240, 280, 34, 14);
        panelImage1.add(progress);
        progress.setBounds(110, 220, 280, 20);

        porcentagem.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        porcentagem.setForeground(new java.awt.Color(255, 255, 255));
        panelImage1.add(porcentagem);
        porcentagem.setBounds(240, 240, 30, 20);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 500, 320);

        setSize(new java.awt.Dimension(500, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private javax.swing.JLabel porcentagem;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
